### ISSUE TITLE
[FEATURE] Dockerizing this project 

### ISSUE THREAD

**Issue by vrushabhgawas14** [codingkatty/mathpylearn#84]
**Describe your idea here.**
To make contributing easier and avoid these environment issues, I think it would be beneficial to containerize the project using Docker. This would ensure that everyone works in a consistent environment without worrying about dependency conflicts or setup problems.

**Anything you'd like to add.**
I would work on these issue.

**Comment by codingkatty** [comment]
Hi, thank you for the suggestion! While containerizing the project with Docker is a great idea, I feel it might be a bit advanced for this stage. Since I'm still learning about it myself and want to keep things simple for beginner contributors, I think we'll hold off on that for now. But I really appreciate your input, thanks again!
